In [1]:
import numpy as  np

loadData = np.load('/home/ExtraData/SceneClass/Data/train_data/farmland/2/Point.npy')
print(loadData)

[[ 1.03999931e+05  4.31955949e+05 -1.53300000e+00]
 [ 1.03999966e+05  4.31956816e+05 -1.48600000e+00]
 [ 1.03999892e+05  4.31956519e+05 -1.47500000e+00]
 ...
 [ 1.04090448e+05  4.32111861e+05 -1.52100000e+00]
 [ 1.04090522e+05  4.32111570e+05 -1.48900000e+00]
 [ 1.04090538e+05  4.32113186e+05 -2.05200000e+00]]


In [ ]:
一个pytorch格式的tensor形状为（32，32，32，32），也就是说有32个通道，每个通道的形状为（32，32，32）。我想把各个通道相同位置的元素取出来各形成一个32维向量，存入一个list中，并把其对应的位置存在另一个list中

2023/11/19 23:49:40

你可以使用以下代码来实现你的需求：

python
import torch

# 创建一个形状为（32，32，32，32）的tensor
tensor = torch.randn(32, 32, 32, 32)

# 将tensor按照第一个维度拆分成32个tensor
channel_tensors = torch.split(tensor, 1, dim=0)

# 初始化两个空的list，用来存储向量和位置
vectors_list = []
positions_list = []

# 遍历每个通道的tensor
for i, channel_tensor in enumerate(channel_tensors):
    # 将每个通道的tensor拉平成一维向量，并转为numpy数组
    vector = channel_tensor.view(-1).numpy()
    # 将向量存入list
    vectors_list.append(vector)
    # 存储对应位置
    positions_list.append(i)

# 打印结果
print(vectors_list)
print(positions_list)
这段代码首先将形状为（32，32，32，32）的tensor按照第一个维度拆分成32个tensor，然后将每个通道的tensor拉平成一维向量并存入一个list中，同时将对应的位置存入另一个list中。

In [ ]:
import torch
import numpy as np

# 创建一个形状为（32，32，32，32）的随机tensor作为示例
tensor = torch.randn(16, 32, 64, 64, 64)

vectors_list = []
indices_list = []

indices = torch.nonzero(tensor)
for idx in indices:
    i, j, k = idx[2], idx[3], idx[4]
    selected_elements = tensor[idx[0], :, idx[2], idx[3], idx[4]]
    vectors_list.append(selected_elements)
    indices_list.append(torch.Tensor([idx[0], idx[2], idx[3], idx[4]]))
f = torch.stack(vectors_list)
c = torch.stack(indices_list)

c = c.numpy()
# 对二维数组进行去重操作，同时返回被删除行的位置
unique_arr, index = np.unique(c, axis=0, return_index=True)

print(vectors_list)
print(indices_list)

In [6]:
import torch

# 创建一个二维tensor
tensor = torch.tensor([[0, 0, 0],
                      [1, 0, 3],
                      [0, 0, 0],
                      [0, 0, 0]])

# 找出含有非零元素的行号
non_zero_rows = torch.nonzero((tensor != 0).any(dim=1)).squeeze()

print(non_zero_rows)


tensor(1)


In [14]:
import torch

# 创建一个形状为（16，32，64，64，64）的随机五维tensor
tensor = torch.ones(16, 32, 64, 64, 64)

# 对第二维度进行求和操作，保持其他维度不变
sum_tensor = torch.sum(tensor, dim=1)

# 输出新的形状为（16，64，64，64）的tensor
print(sum_tensor.shape)

torch.Size([16, 64, 64, 64])


In [ ]:
import torch

# 创建一个五维tensor
tensor = torch.ones(16, 32, 64, 64, 64)  # 生成随机的五维tensor

non_zero_indices = torch.nonzero((tensor.sum(dim=(1))) != 0).squeeze()
value = tensor[non_zero_indices[:, 0], :, non_zero_indices[:, 1], non_zero_indices[:, 2], non_zero_indices[:, 3]]

print(non_zero_indices)


In [4]:
import torch

tensor = torch.Tensor([[ 0,  0,  0,  0,  0],
        [ 5,  6,  7,  5,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

b=torch.nonzero(tensor[1]==5)
print(b)

tensor([[0],
        [3]])


In [6]:
import torch

def remove_duplicate_rows(tensor: torch.Tensor) -> tuple:
    """
    Remove duplicate rows from a 2D PyTorch tensor and return the unique tensor and indices of removed rows.

    Args:
        tensor (torch.Tensor): A 2D PyTorch tensor.

    Returns:
        tuple: A tuple containing the unique tensor and a tensor of indices of removed rows.

    Example:
        >>> import torch
        >>> tensor = torch.tensor([[1, 2], [3, 4], [1, 2], [5, 6]])
        >>> unique_tensor, removed_indices = remove_duplicate_rows(tensor)
        >>> print(unique_tensor)
        tensor([[1, 2],
                [3, 4],
                [5, 6]])
        >>> print(removed_indices)
        tensor([2])
    """
    assert tensor.dim() == 2, "Input tensor must be 2D."

    unique_tensor, inverse_indices = torch.unique(tensor, sorted=True, return_inverse=True, dim=0)
    removed_indices = torch.nonzero(inverse_indices >= tensor.size(0), as_tuple=False)

    return unique_tensor, removed_indices

# Test the function
tensor = torch.tensor([[1, 2], [3, 4], [1, 2], [5, 6], [1, 2], [5, 6], [7, 8]])
unique_tensor, removed_indices = remove_duplicate_rows(tensor)
print(unique_tensor)
print(removed_indices)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([], size=(0, 1), dtype=torch.int64)


In [9]:
import numpy as np

# 创建二维数组
arr = np.array([[7, 8], [1, 2], [3, 4], [1, 2], [5, 6], [1, 2], [5, 6]])

# 对二维数组进行去重操作，同时返回被删除行的位置
unique_arr, index = np.unique(arr, axis=0, return_index=True, return_counts = True)

# 输出去重后的数组和被删除行的位置
print("去重后的数组：", unique_arr)
print("被删除行的位置：", np.setdiff1d(np.arange(len(arr)), index))


去重后的数组： [[1 2]
 [3 4]
 [5 6]
 [7 8]]
被删除行的位置： [3 5 6]


In [11]:
import numpy as np

arr = np.array([6, 5, 1, 2, 3, 2, 1, 3, 4, 5, 6, 4, 5, 6])
unique_values, indices = np.unique(arr, return_index=True)
print(unique_values)  # 输出结果不排序

[1 2 3 4 5 6]


In [1]:
import torch

# 构造二维张量
x = torch.tensor([[1, 2], [3, 4], [1, 2], [5, 6]])

# 对二维张量进行去重
unique_x, indices = torch.unique(x, return_inverse=True, dim=0)

# 打印去重后的结果和被删除行的位置
print("去重后的结果：", unique_x)
print("被删除行的位置：", torch.nonzero(torch.bincount(indices) == 1).flatten())

去重后的结果： tensor([[1, 2],
        [3, 4],
        [5, 6]])
被删除行的位置： tensor([1, 2])


In [2]:
import torch

# 构造二维张量
x = torch.tensor([[1, 2], [3, 4], [1, 2], [5, 6]])

# 对二维张量进行去重
unique_x, indices = torch.unique(x, return_inverse=True, dim=0)

# 打印去重后的结果和被删除行的行号
print("去重后的结果：", unique_x)
deleted_rows = torch.where(torch.bincount(indices) == 1)[0]
print("被删除行的行号：", deleted_rows)

去重后的结果： tensor([[1, 2],
        [3, 4],
        [5, 6]])
被删除行的行号： tensor([1, 2])


In [3]:
import torch

# 二维张量
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])

# 找到重复的行并记录行号
unique_tensor, indices = torch.unique(tensor, dim=0, return_inverse=True)
duplicates = torch.eq(indices, torch.arange(indices.size(0)).unsqueeze(1)).nonzero()[:, 1]

# 打印去重后的张量和被删除行的行号
print("Unique tensor:")
print(unique_tensor)
print("Duplicate rows:")
print(duplicates)

Unique tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Duplicate rows:
tensor([0, 2, 1, 3])


In [3]:
import torch
import numpy as np

torch.manual_seed(42)

# 创建一个形状为（32，32，32，32）的随机tensor作为示例
tensor = torch.randn(16, 32, 32, 32, 32)


for b in range(tensor.size()[0]):
    vectors_list = []
    indices_list = []
    for i in range(tensor.size()[2]):
        for j in range(tensor.size()[3]):
            for k in range(tensor.size()[4]):
                selected_elements = tensor[b, :, i, j, k]
                if torch.any(selected_elements != 0):
                    vectors_list.append(selected_elements)
                    indices_list.append(torch.Tensor([b, i, j, k]))
    if b == 0:
        # 将列表中的张量堆叠起来
        f = torch.stack(vectors_list)
        feats = f.clone()
        c = torch.stack(indices_list)
        coords = c.clone()
    else:
        # 将列表中的张量堆叠起来
        f = torch.stack(vectors_list)
        feats = torch.cat((feats, f))
        c = torch.stack(indices_list)
        coords = torch.cat((coords, c)).type(torch.int)
print(feats)
print(coords)

NameError: name 'np' is not defined

In [12]:
import torch

a = torch.Tensor([0.0])

if a != 0:
    print('0')

In [2]:
import torch

# 创建一个形状为（16，16，16）的三维tensor
tensor = torch.randn(16, 16, 16)

# 将三维tensor转换成一维tensor
flattened_tensor = tensor.view(-1)

# 使用torch.arange生成一组索引
indices = torch.arange(flattened_tensor.size(0))

# 使用torch.unravel_index将一维索引转换回原来的三维索引
indices_3d = torch.unravel_index(indices, tensor.size())

# 遍历每个元素并记录其下标
for i in range(indices_3d[0].size(0)):
    index = (indices_3d[0][i].item(), indices_3d[1][i].item(), indices_3d[2][i].item())
    value = tensor[index]
    # 在这里可以对当前元素进行需要的操作
    print(f"Index: {index}, Value: {value}")


AttributeError: module 'torch' has no attribute 'unravel_index'

In [4]:
import torch

# 假设你的列表是list_of_tensors
list_of_tensors = [torch.randn(23) for _ in range(30)]

# 将列表中的张量堆叠起来
stacked_tensor = torch.stack(list_of_tensors)

# 转置张量
reshaped_tensor = torch.transpose(stacked_tensor, 0, 1)

print(reshaped_tensor.shape)  # 输出：torch.Size([30, 23])


torch.Size([23, 30])


In [ ]:
import torch

# 假设你的列表是list_of_tensors
list_of_tensors = [torch.randn(23) for _ in range(30)]

# 将列表中的张量堆叠起来
stacked_tensor = torch.stack(list_of_tensors)

# 转置张量
reshaped_tensor = torch.transpose(stacked_tensor, 0, 1)

print(reshaped_tensor.shape)  # 输出：torch.Size([30, 23])


In [ ]:
import torch

# 假设你有两个一维张量 tensor1 和 tensor2
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# 将两个张量沿着行的维度进行堆叠
stacked_tensor = torch.stack((tensor1, tensor2))

print(stacked_tensor)
print(stacked_tensor.shape)  # 输出：torch.Size([2, 3])

In [1]:
import torch

# 创建形状为（32，32，32，32）的tensor
tensor = torch.randn(32, 32, 32, 32)

# 按照第一个维度拆分成32个tensor
split_tensors = torch.split(tensor, 1, dim=0)

# 记录每个tensor在原始tensor中的位置
positions = []

# 将每个通道的tensor拉平成一维向量并存入一个list中，同时将对应的位置存入另一个list中
flattened_tensors = []
for i, t in enumerate(split_tensors):
    flattened = t.view(-1)
    flattened_tensors.append(flattened)
    positions.extend([(i, j, k) for j in range(32) for k in range(32)])

# 将list转换为tensor
flattened_tensors = torch.cat(flattened_tensors)
positions = torch.tensor(positions)

print(flattened_tensors.shape)
print(positions.shape)

torch.Size([1048576])
torch.Size([32768, 3])


In [2]:
a = [0, 1, 2, 3]
print(a[:1])

[0]


In [4]:
from torch import nn
import torch

class ResidualBlock(nn.Module):

    def __init__(self, inc, outc, ks=3, stride=1, dilation=1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv3d(inc,
                        outc,
                        kernel_size=ks,
                        dilation=dilation,
                        stride=stride),
            nn.Conv3d(outc, outc, kernel_size=ks, dilation=dilation,
                        stride=1),
        )

        if inc == outc and stride == 1:
            self.downsample = nn.Identity()
        else:
            self.downsample = nn.Sequential(
                nn.Conv3d(inc, outc, kernel_size=1, dilation=1,
                            stride=stride),
            )

        self.relu = nn.ReLU(True)

    def forward(self, x):
        out = self.net(x) + self.downsample(x)
        return out


tensor = torch.rand((2, 3, 198, 198))
print(tensor.shape)
net = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, stride=2)
# net = nn.Sequential(
#             ResidualBlock(3, 4, ks=3, stride=1, dilation=1), # 
#             ResidualBlock(4, 4, ks=3, stride=1, dilation=1),
#         )
out = net(tensor)
print(out.shape)





# self.net = nn.Sequential(
#             spnn.Conv3d(inc,
#                         outc,
#                         kernel_size=ks,
#                         dilation=dilation,
#                         stride=stride),
#             spnn.BatchNorm(outc),
#             spnn.ReLU(True),
#             spnn.Conv3d(outc, outc, kernel_size=ks, dilation=dilation,
#                         stride=1),
#             spnn.BatchNorm(outc),
#         )

#         if inc == outc and stride == 1:
#             self.downsample = nn.Identity()
#         else:
#             self.downsample = nn.Sequential(
#                 spnn.Conv3d(inc, outc, kernel_size=1, dilation=1,
#                             stride=stride),
#                 spnn.BatchNorm(outc),
#             )

#         self.relu = spnn.ReLU(True)

#     def forward(self, x):
#         out = self.relu(self.net(x) + self.downsample(x))
#         return out

torch.Size([2, 3, 198, 198])
torch.Size([2, 3, 98, 98])


In [2]:
import torch
rs_img = torch.randn((2, 3, 20, 40, 60))
y = torch.mean(rs_img, dim=2)
print(y.shape)

torch.Size([2, 3, 40, 60])


In [ ]:
import torch
import torchsparse
import torchsparse.nn as spnn
import torchsparse.nn.functional as F

torch.manual_seed(42)
a = [1,2,3,4,5,6,7,8]
feats = torch.Tensor(a)
num_points = 100
dim = 4
feats = torch.randn([num_points, dim]).cuda()
coords = torch.randint(0, 10, [num_points, 4]).cuda()
coords[:, 0] = 0        # Set batch_idx to 0

spatial_range = (1, 10, 10, 10)
x = torchsparse.SparseTensor(feats, coords, spatial_range = spatial_range)

y = x.dense()

In [2]:
import torch

# 创建一个形状为（2，3，10，10，10）的张量
tensor = torch.randn(2, 3, 10, 10, 10)

# 求第三维的最大值，并返回形状为（2，3，10，10）的张量
max_values, _ = torch.max(tensor, dim=3)
print(max_values)

KeyboardInterrupt: 